### ISSUE TITLE
Coon scripts are injected multiple times, despite no postback.

### ISSUE THREAD

**Issue by cederlof** [Chropez/JournalenCoon#11] opened 2016-01-04 13:08 UTC
![image](https://cloud.githubusercontent.com/assets/1106978/12090155/8378fc4e-b2ec-11e5-867d-acfce213858f.png)

**Comment by Chropez** [comment] 2016-01-04 13:40
Duplicate of issue #9

**Closed as completed by Chropez** 2016-01-04 13:40 UTC
Labels: bug, duplicate
